<?php

declare(strict_types=1);

namespace Admin\Support;

/**
 * ISO 3166-1 alpha-2 country list with a common currency/symbol for each,
 * served to the admin console so pricing and user filters never hard-code a
 * country table into the client.
 *
 * @return list<array{code: string, name: string, currency: string, symbol: string}>
 */
final class Countries
{
    /**
     * @var array<string, array{name: string, currency: string, symbol: string}>
     */
    private const MAP = [
        'AF' => ['name' => 'Afghanistan', 'currency' => 'AFN', 'symbol' => 'Ø‹'],
        'AL' => ['name' => 'Albania', 'currency' => 'ALL', 'symbol' => 'L'],
        'DZ' => ['name' => 'Algeria', 'currency' => 'DZD', 'symbol' => 'Ø¯Ø¬'],
        'AS' => ['name' => 'American Samoa', 'currency' => 'USD', 'symbol' => '$'],
        'AD' => ['name' => 'Andorra', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'AO' => ['name' => 'Angola', 'currency' => 'AOA', 'symbol' => 'Kz'],
        'AI' => ['name' => 'Anguilla', 'currency' => 'XCD', 'symbol' => '$'],
        'AG' => ['name' => 'Antigua and Barbuda', 'currency' => 'XCD', 'symbol' => '$'],
        'AR' => ['name' => 'Argentina', 'currency' => 'ARS', 'symbol' => '$'],
        'AM' => ['name' => 'Armenia', 'currency' => 'AMD', 'symbol' => 'Ö'],
        'AW' => ['name' => 'Aruba', 'currency' => 'AWG', 'symbol' => 'Æ’'],
        'AU' => ['name' => 'Australia', 'currency' => 'AUD', 'symbol' => 'A$'],
        'AT' => ['name' => 'Austria', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'AZ' => ['name' => 'Azerbaijan', 'currency' => 'AZN', 'symbol' => 'â‚¼'],
        'BS' => ['name' => 'Bahamas', 'currency' => 'BSD', 'symbol' => '$'],
        'BH' => ['name' => 'Bahrain', 'currency' => 'BHD', 'symbol' => 'Ø¯.Ø¨'],
        'BD' => ['name' => 'Bangladesh', 'currency' => 'BDT', 'symbol' => 'à§³'],
        'BB' => ['name' => 'Barbados', 'currency' => 'BBD', 'symbol' => '$'],
        'BY' => ['name' => 'Belarus', 'currency' => 'BYN', 'symbol' => 'Br'],
        'BE' => ['name' => 'Belgium', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'BZ' => ['name' => 'Belize', 'currency' => 'BZD', 'symbol' => '$'],
        'BJ' => ['name' => 'Benin', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'BM' => ['name' => 'Bermuda', 'currency' => 'BMD', 'symbol' => '$'],
        'BT' => ['name' => 'Bhutan', 'currency' => 'BTN', 'symbol' => 'Nu.'],
        'BO' => ['name' => 'Bolivia', 'currency' => 'BOB', 'symbol' => 'Bs'],
        'BA' => ['name' => 'Bosnia and Herzegovina', 'currency' => 'BAM', 'symbol' => 'KM'],
        'BW' => ['name' => 'Botswana', 'currency' => 'BWP', 'symbol' => 'P'],
        'BR' => ['name' => 'Brazil', 'currency' => 'BRL', 'symbol' => 'R$'],
        'BN' => ['name' => 'Brunei', 'currency' => 'BND', 'symbol' => '$'],
        'BG' => ['name' => 'Bulgaria', 'currency' => 'BGN', 'symbol' => 'Ð»Ð²'],
        'BF' => ['name' => 'Burkina Faso', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'BI' => ['name' => 'Burundi', 'currency' => 'BIF', 'symbol' => 'Fr'],
        'KH' => ['name' => 'Cambodia', 'currency' => 'KHR', 'symbol' => 'áŸ›'],
        'CM' => ['name' => 'Cameroon', 'currency' => 'XAF', 'symbol' => 'FCFA'],
        'CA' => ['name' => 'Canada', 'currency' => 'CAD', 'symbol' => 'C$'],
        'CV' => ['name' => 'Cape Verde', 'currency' => 'CVE', 'symbol' => 'Esc'],
        'KY' => ['name' => 'Cayman Islands', 'currency' => 'KYD', 'symbol' => '$'],
        'TD' => ['name' => 'Chad', 'currency' => 'XAF', 'symbol' => 'FCFA'],
        'CL' => ['name' => 'Chile', 'currency' => 'CLP', 'symbol' => '$'],
        'CN' => ['name' => 'China', 'currency' => 'CNY', 'symbol' => 'Â¥'],
        'CO' => ['name' => 'Colombia', 'currency' => 'COP', 'symbol' => '$'],
        'KM' => ['name' => 'Comoros', 'currency' => 'KMF', 'symbol' => 'Fr'],
        'CD' => ['name' => 'Congo, Democratic Republic', 'currency' => 'CDF', 'symbol' => 'FC'],
        'CG' => ['name' => 'Congo, Republic', 'currency' => 'XAF', 'symbol' => 'FCFA'],
        'CK' => ['name' => 'Cook Islands', 'currency' => 'NZD', 'symbol' => '$'],
        'CR' => ['name' => 'Costa Rica', 'currency' => 'CRC', 'symbol' => 'â‚¡'],
        'HR' => ['name' => 'Croatia', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'CU' => ['name' => 'Cuba', 'currency' => 'CUP', 'symbol' => '$'],
        'CY' => ['name' => 'Cyprus', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'CZ' => ['name' => 'Czech Republic', 'currency' => 'CZK', 'symbol' => 'KÄ'],
        'DK' => ['name' => 'Denmark', 'currency' => 'DKK', 'symbol' => 'kr'],
        'DJ' => ['name' => 'Djibouti', 'currency' => 'DJF', 'symbol' => 'Fdj'],
        'DM' => ['name' => 'Dominica', 'currency' => 'XCD', 'symbol' => '$'],
        'DO' => ['name' => 'Dominican Republic', 'currency' => 'DOP', 'symbol' => 'RD$'],
        'EC' => ['name' => 'Ecuador', 'currency' => 'USD', 'symbol' => '$'],
        'EG' => ['name' => 'Egypt', 'currency' => 'EGP', 'symbol' => 'EÂ£'],
        'SV' => ['name' => 'El Salvador', 'currency' => 'USD', 'symbol' => '$'],
        'GQ' => ['name' => 'Equatorial Guinea', 'currency' => 'XAF', 'symbol' => 'FCFA'],
        'ER' => ['name' => 'Eritrea', 'currency' => 'ERN', 'symbol' => 'Nfk'],
        'EE' => ['name' => 'Estonia', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'ET' => ['name' => 'Ethiopia', 'currency' => 'ETB', 'symbol' => 'Br'],
        'FJ' => ['name' => 'Fiji', 'currency' => 'FJD', 'symbol' => '$'],
        'FI' => ['name' => 'Finland', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'FR' => ['name' => 'France', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'GF' => ['name' => 'French Guiana', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'PF' => ['name' => 'French Polynesia', 'currency' => 'XPF', 'symbol' => 'F'],
        'GA' => ['name' => 'Gabon', 'currency' => 'XAF', 'symbol' => 'FCFA'],
        'GM' => ['name' => 'Gambia', 'currency' => 'GMD', 'symbol' => 'D'],
        'GE' => ['name' => 'Georgia', 'currency' => 'GEL', 'symbol' => 'â‚¾'],
        'DE' => ['name' => 'Germany', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'GH' => ['name' => 'Ghana', 'currency' => 'GHS', 'symbol' => 'â‚µ'],
        'GI' => ['name' => 'Gibraltar', 'currency' => 'GIP', 'symbol' => 'Â£'],
        'GR' => ['name' => 'Greece', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'GL' => ['name' => 'Greenland', 'currency' => 'DKK', 'symbol' => 'kr'],
        'GD' => ['name' => 'Grenada', 'currency' => 'XCD', 'symbol' => '$'],
        'GP' => ['name' => 'Guadeloupe', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'GU' => ['name' => 'Guam', 'currency' => 'USD', 'symbol' => '$'],
        'GT' => ['name' => 'Guatemala', 'currency' => 'GTQ', 'symbol' => 'Q'],
        'GN' => ['name' => 'Guinea', 'currency' => 'GNF', 'symbol' => 'Fr'],
        'GW' => ['name' => 'Guinea-Bissau', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'GY' => ['name' => 'Guyana', 'currency' => 'GYD', 'symbol' => '$'],
        'HT' => ['name' => 'Haiti', 'currency' => 'HTG', 'symbol' => 'G'],
        'HN' => ['name' => 'Honduras', 'currency' => 'HNL', 'symbol' => 'L'],
        'HK' => ['name' => 'Hong Kong', 'currency' => 'HKD', 'symbol' => 'HK$'],
        'HU' => ['name' => 'Hungary', 'currency' => 'HUF', 'symbol' => 'Ft'],
        'IS' => ['name' => 'Iceland', 'currency' => 'ISK', 'symbol' => 'kr'],
        'IN' => ['name' => 'India', 'currency' => 'INR', 'symbol' => 'â‚¹'],
        'ID' => ['name' => 'Indonesia', 'currency' => 'IDR', 'symbol' => 'Rp'],
        'IR' => ['name' => 'Iran', 'currency' => 'IRR', 'symbol' => 'ï·¼'],
        'IQ' => ['name' => 'Iraq', 'currency' => 'IQD', 'symbol' => 'Ø¹.Ø¯'],
        'IE' => ['name' => 'Ireland', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'IL' => ['name' => 'Israel', 'currency' => 'ILS', 'symbol' => 'â‚ª'],
        'IT' => ['name' => 'Italy', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'JM' => ['name' => 'Jamaica', 'currency' => 'JMD', 'symbol' => '$'],
        'JP' => ['name' => 'Japan', 'currency' => 'JPY', 'symbol' => 'Â¥'],
        'JO' => ['name' => 'Jordan', 'currency' => 'JOD', 'symbol' => 'Ø¯.Ø§'],
        'KZ' => ['name' => 'Kazakhstan', 'currency' => 'KZT', 'symbol' => 'â‚¸'],
        'KE' => ['name' => 'Kenya', 'currency' => 'KES', 'symbol' => 'KSh'],
        'KI' => ['name' => 'Kiribati', 'currency' => 'AUD', 'symbol' => '$'],
        'KW' => ['name' => 'Kuwait', 'currency' => 'KWD', 'symbol' => 'Ø¯.Ùƒ'],
        'KG' => ['name' => 'Kyrgyzstan', 'currency' => 'KGS', 'symbol' => 'Ñ'],
        'LA' => ['name' => 'Laos', 'currency' => 'LAK', 'symbol' => 'â‚­'],
        'LV' => ['name' => 'Latvia', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'LB' => ['name' => 'Lebanon', 'currency' => 'LBP', 'symbol' => 'Ù„.Ù„'],
        'LS' => ['name' => 'Lesotho', 'currency' => 'LSL', 'symbol' => 'L'],
        'LR' => ['name' => 'Liberia', 'currency' => 'LRD', 'symbol' => '$'],
        'LY' => ['name' => 'Libya', 'currency' => 'LYD', 'symbol' => 'Ù„.Ø¯'],
        'LI' => ['name' => 'Liechtenstein', 'currency' => 'CHF', 'symbol' => 'Fr'],
        'LT' => ['name' => 'Lithuania', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'LU' => ['name' => 'Luxembourg', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'MO' => ['name' => 'Macao', 'currency' => 'MOP', 'symbol' => 'MOP$'],
        'MK' => ['name' => 'North Macedonia', 'currency' => 'MKD', 'symbol' => 'Ð´ÐµÐ½'],
        'MG' => ['name' => 'Madagascar', 'currency' => 'MGA', 'symbol' => 'Ar'],
        'MW' => ['name' => 'Malawi', 'currency' => 'MWK', 'symbol' => 'MK'],
        'MY' => ['name' => 'Malaysia', 'currency' => 'MYR', 'symbol' => 'RM'],
        'MV' => ['name' => 'Maldives', 'currency' => 'MVR', 'symbol' => 'Rf'],
        'ML' => ['name' => 'Mali', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'MT' => ['name' => 'Malta', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'MH' => ['name' => 'Marshall Islands', 'currency' => 'USD', 'symbol' => '$'],
        'MQ' => ['name' => 'Martinique', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'MR' => ['name' => 'Mauritania', 'currency' => 'MRU', 'symbol' => 'UM'],
        'MU' => ['name' => 'Mauritius', 'currency' => 'MUR', 'symbol' => 'â‚¨'],
        'MX' => ['name' => 'Mexico', 'currency' => 'MXN', 'symbol' => '$'],
        'FM' => ['name' => 'Micronesia', 'currency' => 'USD', 'symbol' => '$'],
        'MD' => ['name' => 'Moldova', 'currency' => 'MDL', 'symbol' => 'L'],
        'MC' => ['name' => 'Monaco', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'MN' => ['name' => 'Mongolia', 'currency' => 'MNT', 'symbol' => 'â‚®'],
        'ME' => ['name' => 'Montenegro', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'MA' => ['name' => 'Morocco', 'currency' => 'MAD', 'symbol' => 'Ø¯.Ù….'],
        'MZ' => ['name' => 'Mozambique', 'currency' => 'MZN', 'symbol' => 'MT'],
        'MM' => ['name' => 'Myanmar', 'currency' => 'MMK', 'symbol' => 'K'],
        'NA' => ['name' => 'Namibia', 'currency' => 'NAD', 'symbol' => '$'],
        'NR' => ['name' => 'Nauru', 'currency' => 'AUD', 'symbol' => '$'],
        'NP' => ['name' => 'Nepal', 'currency' => 'NPR', 'symbol' => 'â‚¨'],
        'NL' => ['name' => 'Netherlands', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'NC' => ['name' => 'New Caledonia', 'currency' => 'XPF', 'symbol' => 'F'],
        'NZ' => ['name' => 'New Zealand', 'currency' => 'NZD', 'symbol' => '$'],
        'NI' => ['name' => 'Nicaragua', 'currency' => 'NIO', 'symbol' => 'C$'],
        'NE' => ['name' => 'Niger', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'NG' => ['name' => 'Nigeria', 'currency' => 'NGN', 'symbol' => 'â‚¦'],
        'NU' => ['name' => 'Niue', 'currency' => 'NZD', 'symbol' => '$'],
        'KP' => ['name' => 'North Korea', 'currency' => 'KPW', 'symbol' => 'â‚©'],
        'MP' => ['name' => 'Northern Mariana Islands', 'currency' => 'USD', 'symbol' => '$'],
        'NO' => ['name' => 'Norway', 'currency' => 'NOK', 'symbol' => 'kr'],
        'OM' => ['name' => 'Oman', 'currency' => 'OMR', 'symbol' => 'Ø±.Ø¹.'],
        'PK' => ['name' => 'Pakistan', 'currency' => 'PKR', 'symbol' => 'â‚¨'],
        'PW' => ['name' => 'Palau', 'currency' => 'USD', 'symbol' => '$'],
        'PA' => ['name' => 'Panama', 'currency' => 'PAB', 'symbol' => 'B/.'],
        'PG' => ['name' => 'Papua New Guinea', 'currency' => 'PGK', 'symbol' => 'K'],
        'PY' => ['name' => 'Paraguay', 'currency' => 'PYG', 'symbol' => 'â‚²'],
        'PE' => ['name' => 'Peru', 'currency' => 'PEN', 'symbol' => 'S/'],
        'PH' => ['name' => 'Philippines', 'currency' => 'PHP', 'symbol' => 'â‚±'],
        'PL' => ['name' => 'Poland', 'currency' => 'PLN', 'symbol' => 'zÅ‚'],
        'PT' => ['name' => 'Portugal', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'PR' => ['name' => 'Puerto Rico', 'currency' => 'USD', 'symbol' => '$'],
        'QA' => ['name' => 'Qatar', 'currency' => 'QAR', 'symbol' => 'Ø±.Ù‚'],
        'RE' => ['name' => 'RÃ©union', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'RO' => ['name' => 'Romania', 'currency' => 'RON', 'symbol' => 'lei'],
        'RU' => ['name' => 'Russia', 'currency' => 'RUB', 'symbol' => 'â‚½'],
        'RW' => ['name' => 'Rwanda', 'currency' => 'RWF', 'symbol' => 'Fr'],
        'BL' => ['name' => 'Saint BarthÃ©lemy', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'KN' => ['name' => 'Saint Kitts and Nevis', 'currency' => 'XCD', 'symbol' => '$'],
        'LC' => ['name' => 'Saint Lucia', 'currency' => 'XCD', 'symbol' => '$'],
        'PM' => ['name' => 'Saint Pierre and Miquelon', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'VC' => ['name' => 'Saint Vincent and the Grenadines', 'currency' => 'XCD', 'symbol' => '$'],
        'WS' => ['name' => 'Samoa', 'currency' => 'WST', 'symbol' => 'WS$'],
        'SM' => ['name' => 'San Marino', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'ST' => ['name' => 'Sao Tome and Principe', 'currency' => 'STN', 'symbol' => 'Db'],
        'SA' => ['name' => 'Saudi Arabia', 'currency' => 'SAR', 'symbol' => 'Ø±.Ø³'],
        'SN' => ['name' => 'Senegal', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'RS' => ['name' => 'Serbia', 'currency' => 'RSD', 'symbol' => 'Ð´Ð¸Ð½'],
        'SC' => ['name' => 'Seychelles', 'currency' => 'SCR', 'symbol' => 'â‚¨'],
        'SL' => ['name' => 'Sierra Leone', 'currency' => 'SLL', 'symbol' => 'Le'],
        'SG' => ['name' => 'Singapore', 'currency' => 'SGD', 'symbol' => 'S$'],
        'SK' => ['name' => 'Slovakia', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'SI' => ['name' => 'Slovenia', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'SB' => ['name' => 'Solomon Islands', 'currency' => 'SBD', 'symbol' => '$'],
        'SO' => ['name' => 'Somalia', 'currency' => 'SOS', 'symbol' => 'Sh'],
        'ZA' => ['name' => 'South Africa', 'currency' => 'ZAR', 'symbol' => 'R'],
        'KR' => ['name' => 'South Korea', 'currency' => 'KRW', 'symbol' => 'â‚©'],
        'SS' => ['name' => 'South Sudan', 'currency' => 'SSP', 'symbol' => 'Â£'],
        'ES' => ['name' => 'Spain', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'LK' => ['name' => 'Sri Lanka', 'currency' => 'LKR', 'symbol' => 'â‚¨'],
        'SD' => ['name' => 'Sudan', 'currency' => 'SDG', 'symbol' => 'Â£'],
        'SR' => ['name' => 'Suriname', 'currency' => 'SRD', 'symbol' => '$'],
        'SJ' => ['name' => 'Svalbard and Jan Mayen', 'currency' => 'NOK', 'symbol' => 'kr'],
        'SZ' => ['name' => 'Eswatini', 'currency' => 'SZL', 'symbol' => 'L'],
        'SE' => ['name' => 'Sweden', 'currency' => 'SEK', 'symbol' => 'kr'],
        'CH' => ['name' => 'Switzerland', 'currency' => 'CHF', 'symbol' => 'Fr'],
        'SY' => ['name' => 'Syria', 'currency' => 'SYP', 'symbol' => 'Â£'],
        'TW' => ['name' => 'Taiwan', 'currency' => 'TWD', 'symbol' => 'NT$'],
        'TJ' => ['name' => 'Tajikistan', 'currency' => 'TJS', 'symbol' => 'Ð…Ðœ'],
        'TZ' => ['name' => 'Tanzania', 'currency' => 'TZS', 'symbol' => 'Sh'],
        'TH' => ['name' => 'Thailand', 'currency' => 'THB', 'symbol' => 'à¸¿'],
        'TL' => ['name' => 'Timor-Leste', 'currency' => 'USD', 'symbol' => '$'],
        'TG' => ['name' => 'Togo', 'currency' => 'XOF', 'symbol' => 'Fr'],
        'TK' => ['name' => 'Tokelau', 'currency' => 'NZD', 'symbol' => '$'],
        'TO' => ['name' => 'Tonga', 'currency' => 'TOP', 'symbol' => 'T$'],
        'TT' => ['name' => 'Trinidad and Tobago', 'currency' => 'TTD', 'symbol' => '$'],
        'TN' => ['name' => 'Tunisia', 'currency' => 'TND', 'symbol' => 'Ø¯.Øª'],
        'TR' => ['name' => 'Turkey', 'currency' => 'TRY', 'symbol' => 'â‚º'],
        'TM' => ['name' => 'Turkmenistan', 'currency' => 'TMT', 'symbol' => 'm'],
        'TV' => ['name' => 'Tuvalu', 'currency' => 'AUD', 'symbol' => '$'],
        'UG' => ['name' => 'Uganda', 'currency' => 'UGX', 'symbol' => 'USh'],
        'UA' => ['name' => 'Ukraine', 'currency' => 'UAH', 'symbol' => 'â‚´'],
        'AE' => ['name' => 'United Arab Emirates', 'currency' => 'AED', 'symbol' => 'Ø¯.Ø¥'],
        'GB' => ['name' => 'United Kingdom', 'currency' => 'GBP', 'symbol' => 'Â£'],
        'US' => ['name' => 'United States', 'currency' => 'USD', 'symbol' => '$'],
        'UY' => ['name' => 'Uruguay', 'currency' => 'UYU', 'symbol' => '$U'],
        'UZ' => ['name' => 'Uzbekistan', 'currency' => 'UZS', 'symbol' => 'soâ€˜m'],
        'VU' => ['name' => 'Vanuatu', 'currency' => 'VUV', 'symbol' => 'VT'],
        'VA' => ['name' => 'Vatican City', 'currency' => 'EUR', 'symbol' => 'â‚¬'],
        'VE' => ['name' => 'Venezuela', 'currency' => 'VES', 'symbol' => 'Bs'],
        'VN' => ['name' => 'Vietnam', 'currency' => 'VND', 'symbol' => 'â‚«'],
        'VI' => ['name' => 'Virgin Islands, U.S.', 'currency' => 'USD', 'symbol' => '$'],
        'YE' => ['name' => 'Yemen', 'currency' => 'YER', 'symbol' => 'ï·¼'],
        'ZM' => ['name' => 'Zambia', 'currency' => 'ZMW', 'symbol' => 'ZK'],
        'ZW' => ['name' => 'Zimbabwe', 'currency' => 'ZWL', 'symbol' => '$'],
    ];

    /**
     * @return list<array{code: string, name: string, currency: string, symbol: string}>
     */
    public static function all(): array
    {
        $rows = [];
        foreach (self::MAP as $code => $row) {
            $rows[] = [
                'code' => $code,
                'name' => $row['name'],
                'currency' => $row['currency'],
                'symbol' => $row['symbol'],
            ];
        }

        usort($rows, static fn (array $a, array $b): int => strcmp($a['name'], $b['name']));

        return $rows;
    }

    /**
     * @return array{name: string, currency: string, symbol: string}|null
     */
    public static function find(string $code): ?array
    {
        return self::MAP[strtoupper($code)] ?? null;
    }
}